# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Russell Barnes
tagline:          'The Jekyll Butler'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://russb78.github.io

author:
  name:           'Russell Barnes'
  url:            https://twitter.com/another_russell

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
