# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rosie Summer
tagline:          'Pictures of a special little lady'
description:      'Somewhere to keep memories safe.'
url:              http://russb78.github.io

author:
  name:           'Russell Barnes'
  url:            https://twitter.com/another_russell

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/russb78/russb78.github.io

# This is the list of pages to include in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
